name: Create Release

permissions:
  contents: write
  issues: write

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Load variables from .env
        run: |
          while IFS='=' read -r key value; do
            echo "$key=$value" >> $GITHUB_ENV;
          done < .env

      - name: Debug environment variables
        run: |
          echo "VERSION=${{ env.VERSION }}"
          echo "EXTENSION=${{ env.EXTENSION }}"
          echo "MANIFEST=${{ env.MANIFEST }}"

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Update module's XML manifest
        run: python update_manifest.py ${{ env.EXTENSION }} ${{ env.MANIFEST }} ${{ env.VERSION }}

      - name: Zip the module folder
        run: zip -r ${{ env.EXTENSION }}-${{ env.VERSION }}.zip ${{ env.EXTENSION }}/

      - name: Compute SHA512 checksum
        run: |
          sha512sum ${{ env.EXTENSION }}-${{ env.VERSION }}.zip > ${{ env.EXTENSION }}-${{ env.VERSION }}.zip.sha512
          SHA512=$(cat ${{ env.EXTENSION }}-${{ env.VERSION }}.zip.sha512 | cut -d' ' -f1)
          echo "SHA512=$SHA512" >> $GITHUB_ENV

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ env.VERSION }}
          release_name: Release ${{ env.VERSION }}
          draft: false
          prerelease: false

      - name: Upload Release Asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./${{ env.EXTENSION }}-${{ env.VERSION }}.zip
          asset_name: ${{ env.EXTENSION }}-${{ env.VERSION }}.zip
          asset_content_type: application/zip

      - name: Update update.xml and commit changes
        run: |
          DOWNLOAD_URL="https://github.com/pe7er/${{ env.EXTENSION }}/releases/download/${{ env.VERSION }}/${{ env.EXTENSION }}-${{ env.VERSION }}.zip"
          python update_update_xml.py ${{ env.VERSION }} $DOWNLOAD_URL ${{ env.SHA512 }}
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add update.xml ${{ env.EXTENSION }}/${{ env.MANIFEST }}
          git commit -m "Update version to ${{ env.VERSION }}"
          git push
